baseURL = "http://paasbox.io/"
languageCode = "en-us"
title = "paasbox"

[params]
	# General information
	author = "Ian Kent"
	description = "PaaS - in a box!"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/paasbox/paasbox"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "paasbox"
	github  = "paasbox"
	email   = "hello@paasbox.io"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 5

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Configuration"
	url    = "configuration/"
	weight = 20

[[menu.main]]
	name   = "Workspaces"
	url    = "workspaces/"
	weight = 50

[[menu.main]]
	name   = "Tasks"
	url    = "tasks/"
	weight = 100

[[menu.main]]
	name   = "Load balancer"
	url    = "load-balancer/"
	weight = 150

[[menu.main]]
	name   = "Logging"
	url    = "logging/"
	weight = 200

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 300

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 400


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
