all:
	hugo server --buildDrafts --theme=hugo-material-docs

build:
	hugo --theme=hugo-material-docs -d ../../paasbox.github.io
	@echo
	@echo Commit changes to paasbox.github.io and push to GitHub

.PHONY: all
